<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJbPzIxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJbPzIxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJbPzIxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJbPzIxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJbPzIxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JbPzIxx',
    'container.build_id' => 'a8edfa6f',
    'container.build_time' => 1681314858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJbPzIxx');
