<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhYNYxt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhYNYxt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYhYNYxt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYhYNYxt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYhYNYxt\App_KernelDevDebugContainer([
    'container.build_hash' => 'YhYNYxt',
    'container.build_id' => '37d9e055',
    'container.build_time' => 1682434362,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhYNYxt');
