<?php

namespace ContainerUAdWpHg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gd3E3IZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gd3E3IZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gd3E3IZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'readtime' => ['privates', 'App\\Service\\ReadTime', 'getReadTimeService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'readtime' => 'App\\Service\\ReadTime',
        ]);
    }
}
