<?php

namespace ContainerUAdWpHg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReadTimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ReadTime' shared autowired service.
     *
     * @return \App\Service\ReadTime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReadTime.php';

        return $container->privates['App\\Service\\ReadTime'] = new \App\Service\ReadTime();
    }
}
