<?php

namespace Container6a5j3Tl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J6RelyXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j6RelyX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j6RelyX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.j6RelyX.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.j6RelyX": it references class "App\\Entity\\Article" but no such service exists.'],
            'readtime' => ['privates', 'App\\Service\\ReadTime', 'getReadTimeService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'readtime' => 'App\\Service\\ReadTime',
        ]);
    }
}
